---

# See the documentation on https://docs.ansible.com/ansible/latest/modules/digital_ocean_droplet_module.html

- name: Install nginx.
  apt:
    name: nginx
    state: "{{ nginx_letsencrypt_host_state }}"
    install_recommends: no
    default_release: "{{ nginx_letsencrypt_host_default_release }}"
